services:
  rank-api:
    image: rank:latest
    container_name: rank-rinshankaiho-fun
    restart: always
    # ports:
    #   - "127.0.0.1:8000:8000"
    network_mode: host
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
      - ./.env:/app/.env
      - ./main.py:/app/main.py
    environment:
      - TZ=Asia/Shanghai 
